; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=ez80-code16 < %s | FileCheck %s --check-prefixes=EZ80-CODE16
; RUN: llc -mtriple=ez80 < %s | FileCheck %s --check-prefixes=EZ80

;define i8 @load.p1i8(i8 addrspace(1)*) {
;  load i8, i8 addrspace(1)* %0
;  ret i8 %2
;}
;
;define i16 @load.p1i16(i16 addrspace(1)*) {
;  load i16, i16 addrspace(1)* %0
;  ret i16 %2
;}
;
;define i32 @load.p1i32(i32 addrspace(1)*) {
;  load i32, i32 addrspace(1)* %0
;  ret i32 %2
;}
;
;define i64 @load.p1i64(i64 addrspace(1)*) {
;  load i64, i64 addrspace(1)* %0
;  ret i64 %2
;}
;
;define void @store.p1i8(i8, i8 addrspace(1)*) {
;  store i8 %0, i8 addrspace(1)* %1
;  ret void
;}
;
;define void @store.p1i16(i16, i16 addrspace(1)*) {
;  store i16 %0, i16 addrspace(1)* %1
;  ret void
;}
;
;define void @store.p1i32(i32, i32 addrspace(1)*) {
;  store i32 %0, i32 addrspace(1)* %1
;  ret void
;}
;
;define void @store.p1i64(i64, i64 addrspace(1)*) {
;  store i64 %0, i64 addrspace(1)* %1
;  ret void
;}
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; EZ80: {{.*}}
; EZ80-CODE16: {{.*}}
